;/*FB_PKG_DELIM*/

__d("askForRecommemdationsTransform",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){a.askForRecommemdations==null?c(b):c(babelHelpers["extends"]({},b,{placelist_data:{is_placelist_post:!0,placelist_within_page:a.askForRecommemdations.placeID}}))}f["default"]=a}),66);
__d("RoomCardImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744277");b=d("FalcoLoggerInternal").create("room_card_impression",a);e=b;g["default"]=e}),98);
__d("RoomCardTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744280");b=d("FalcoLoggerInternal").create("room_card_tap",a);e=b;g["default"]=e}),98);
__d("CommunityMessagingRoomsClientEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2503");b=d("FalcoLoggerInternal").create("community_messaging_rooms_client_event",a);e=b;g["default"]=e}),98);
__d("RoomCreateSuccessFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1829151");b=d("FalcoLoggerInternal").create("room_create_success",a);e=b;g["default"]=e}),98);
__d("RoomCreateTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744282");b=d("FalcoLoggerInternal").create("room_create_tap",a);e=b;g["default"]=e}),98);
__d("RoomCreationFailFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744285");b=d("FalcoLoggerInternal").create("room_creation_fail",a);e=b;g["default"]=e}),98);
__d("RoomCreationFlowSuccessFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744287");b=d("FalcoLoggerInternal").create("room_creation_flow_success",a);e=b;g["default"]=e}),98);
__d("RoomEmptyCardSheetImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744293");b=d("FalcoLoggerInternal").create("room_empty_card_sheet_impression",a);e=b;g["default"]=e}),98);
__d("RoomEndTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744294");b=d("FalcoLoggerInternal").create("room_end_tap",a);e=b;g["default"]=e}),98);
__d("RoomGroupRoomInviteParticipantsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2062");b=d("FalcoLoggerInternal").create("room_group_room_invite_participants",a);e=b;g["default"]=e}),98);
__d("RoomGroupRoomListViewImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744296");b=d("FalcoLoggerInternal").create("room_group_room_list_view_impression",a);e=b;g["default"]=e}),98);
__d("RoomGroupRoomListViewItemTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744297");b=d("FalcoLoggerInternal").create("room_group_room_list_view_item_tap",a);e=b;g["default"]=e}),98);
__d("RoomGroupRoomRhcImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744298");b=d("FalcoLoggerInternal").create("room_group_room_rhc_impression",a);e=b;g["default"]=e}),98);
__d("RoomInterestTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744299");b=d("FalcoLoggerInternal").create("room_interest_tap",a);e=b;g["default"]=e}),98);
__d("RoomJoinTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744302");b=d("FalcoLoggerInternal").create("room_join_tap",a);e=b;g["default"]=e}),98);
__d("RoomLobbySheetImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744305");b=d("FalcoLoggerInternal").create("room_lobby_sheet_impression",a);e=b;g["default"]=e}),98);
__d("RoomMessageTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744314");b=d("FalcoLoggerInternal").create("room_message_tap",a);e=b;g["default"]=e}),98);
__d("RoomPromotionUnitImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744315");b=d("FalcoLoggerInternal").create("room_promotion_unit_impression",a);e=b;g["default"]=e}),98);
__d("RoomPromotionUnitTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744316");b=d("FalcoLoggerInternal").create("room_promotion_unit_tap",a);e=b;g["default"]=e}),98);
__d("RoomSelfCardButtonTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744320");b=d("FalcoLoggerInternal").create("room_self_card_button_tap",a);e=b;g["default"]=e}),98);
__d("RoomSelfCardTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744321");b=d("FalcoLoggerInternal").create("room_self_card_tap",a);e=b;g["default"]=e}),98);
__d("RoomSettingSheetImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744323");b=d("FalcoLoggerInternal").create("room_setting_sheet_impression",a);e=b;g["default"]=e}),98);
__d("RoomTrayImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744329");b=d("FalcoLoggerInternal").create("room_tray_impression",a);e=b;g["default"]=e}),98);
__d("RoomUpdateTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744332");b=d("FalcoLoggerInternal").create("room_update_tap",a);e=b;g["default"]=e}),98);
__d("TapReportToFacebookFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2727");b=d("FalcoLoggerInternal").create("tap_report_to_facebook",a);e=b;g["default"]=e}),98);