;/*FB_PKG_DELIM*/

__d("GroupsCometPresenceGroupShownInGroupsTabLogger_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometPresenceGroupShownInGroupsTabLogger_group",selections:[{args:null,kind:"FragmentSpread",name:"useGroupsCometIsProfileDelegateGroup_group"}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("useGroupsCometIsProfileDelegateGroup_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useGroupsCometIsProfileDelegateGroup_group",selections:[{alias:null,args:null,concreteType:"GroupNavigationInfo",kind:"LinkedField",name:"navigation_info",plural:!1,selections:[{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"destination",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],storageKey:null}],storageKey:null}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("CometMenuItemRadio.react",["ix","CometIcon.react","CometMenuItemBase.react","CometMenuItemIcon.react","fbicon","react"],(function(a,b,c,d,e,f,g,h){"use strict";var i=d("react");function a(a,b){var e=a.disabled,f=a.icon,g=a.iconColor,j=a.iconStyle,k=a.isSelected,l=a.radioStyle;l=l===void 0?"default":l;a=babelHelpers.objectWithoutPropertiesLoose(a,["disabled","icon","iconColor","iconStyle","isSelected","radioStyle"]);l==="checkmark"?l=k?i.jsx(c("CometIcon.react"),{color:e===!0?"disabled":"highlight",icon:d("fbicon")._(h("477814"),20)}):void 0:l=k?i.jsx(c("CometIcon.react"),{color:e===!0?"disabled":"highlight",icon:d("fbicon")._(h("621399"),20)}):i.jsx(c("CometIcon.react"),{color:e===!0?"disabled":"secondary",icon:d("fbicon")._(h("545517"),20)});return i.jsx(c("CometMenuItemBase.react"),babelHelpers["extends"]({},a,{"aria-checked":k,aux:l,disabled:e,iconNode:f!=null?i.jsx(c("CometMenuItemIcon.react"),{icon:f,iconColor:g,use:j}):void 0,ref:b,role:"menuitemradio"}))}a.displayName=a.name+" [from "+f.id+"]";b=i.forwardRef(a);g["default"]=b}),98);
__d("PublicEventCometRSVPButtonStrings",["fbt","react"],(function(a,b,c,d,e,f,g,h){"use strict";d("react");function a(a){return a==="GOING"?h._("__JHASH__I74xO2khJDt__JHASH__"):h._("__JHASH__Oz3cVHrpTIY__JHASH__")}a.displayName=a.name+" [from "+f.id+"]";function b(a){return a==="WATCHED"?h._("__JHASH__PSEKKGP96nF__JHASH__"):h._("__JHASH__2qkjQUh42sG__JHASH__")}b.displayName=b.name+" [from "+f.id+"]";function c(a){return a==="WATCHED"?h._("__JHASH__mW930W3sXs7__JHASH__"):h._("__JHASH__h2mdzk1ue9H__JHASH__")}c.displayName=c.name+" [from "+f.id+"]";function e(){return h._("__JHASH__xoeLuaGKq5s__JHASH__")}e.displayName=e.name+" [from "+f.id+"]";d=h._("__JHASH__wKrA40eWj5X__JHASH__");f=h._("__JHASH__ua7NfNkErF9__JHASH__");g.Going=a;g.Interested=b;g.Remove=c;g.Purchase=e;g.thisEventDate=d;g.allEventSeries=f}),98);
__d("useGroupsCometIsProfileDelegateGroup",["CometRelay","useGroupsCometIsProfileDelegateGroup_group.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a){a=a.group$key;a=d("CometRelay").useFragment(h!==void 0?h:h=b("useGroupsCometIsProfileDelegateGroup_group.graphql"),a);return((a=a.navigation_info)==null?void 0:(a=a.destination)==null?void 0:a.__typename)==="User"}g["default"]=a}),98);
__d("GroupsCometPresenceGroupShownInGroupsTabLogger.react",["CometRelay","GroupsCometPresenceGroupShownInGroupsTabLogger_group.graphql","QuickPerformanceLogger","qpl","react","useCurrentRoute","useGroupsCometIsProfileDelegateGroup","useRouteReferrer"],(function(a,b,c,d,e,f,g){"use strict";var h;e=d("react");var i=e.useEffect,j=e.useRef,k=c("qpl")._(759373195,"8111");function a(a){a=a.group$key;a=d("CometRelay").useFragment(h!==void 0?h:h=b("GroupsCometPresenceGroupShownInGroupsTabLogger_group.graphql"),a);var e=j(!1),f=c("useRouteReferrer")(),g=c("useCurrentRoute")(),l=c("useGroupsCometIsProfileDelegateGroup")({group$key:a});i(function(){if(!l)return;if(e.current===!1){var a;e.current=!0;a={string:{entity_key_entity_type:g==null?void 0:(a=g.entityKeyConfig)==null?void 0:(a=a.entity_type)==null?void 0:a.value,entity_key_section:g==null?void 0:(a=g.entityKeyConfig)==null?void 0:(a=a.section)==null?void 0:a.value,is_initial_page_load:String((f==null?void 0:f.actorID)===void 0),referrer_navigation_type:f==null?void 0:f.navigationType,referrer_trace_policy:f==null?void 0:f.tracePolicy,route_type:g==null?void 0:g.type,route_url:g==null?void 0:g.url}};c("QuickPerformanceLogger").markerStart(k);c("QuickPerformanceLogger").markerAnnotate(k,a);c("QuickPerformanceLogger").markerEnd(k,2)}},[]);return null}g["default"]=a}),98);
__d("CmGeneralChatAutoCreationFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("4578");b=d("FalcoLoggerInternal").create("cm_general_chat_auto_creation",a);e=b;g["default"]=e}),98);
__d("CrisisClickUnitFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1743531");b=d("FalcoLoggerInternal").create("crisis_click_unit",a);e=b;g["default"]=e}),98);
__d("CrisisToolViewPageFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1743532");b=d("FalcoLoggerInternal").create("crisis_tool_view_page",a);e=b;g["default"]=e}),98);
__d("CrisisViewModuleFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1743533");b=d("FalcoLoggerInternal").create("crisis_view_module",a);e=b;g["default"]=e}),98);
__d("CrisisViewUnitFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1743534");b=d("FalcoLoggerInternal").create("crisis_view_unit",a);e=b;g["default"]=e}),98);
__d("EventsActionsSrCoreFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1845787");b=d("FalcoLoggerInternal").create("events_actions_sr_core",a);e=b;g["default"]=e}),98);